openapi: "3.0.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: API First Article

servers:
  - url: http://localhost:5000/api
    description: Development API server